Add setup
Aseadd/Leaderboard pull request #3
Opened 2022-08-23 23:18 UTC by Aseadd

2022-08-23 23:27 UTC, Aseadd commented
### **Commits Done So Far**

✔️ Setup Webpack
✔️ Setup Gitflow
✔️ Add plain HTML file
✔️ Add ES6 modules

2022-08-24 08:55 UTC, elmar8287 requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Create job done with setup the project 👍 

## Required Changes ♻️

- [ ] You PR ready for APPROVE, but there is only one issue you have to fix:
- Please, consider fixing the PR description. You added it in a comment, but you have to put it in the PR description section. Here is some instruction on how to do it:
<img width="930" alt="Screen Shot 2022-08-24 at 12 46 04" src="https://user-images.githubusercontent.com/49064106/186375729-2630049e-1835-4aee-ab81-88e2df179c06.png">


## Optional suggestions

- Please, find my OPTIONAL suggestion under the review 👍 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 08:55 UTC, elmar8287 commented on README.md
> +Contributions, issues, and feature requests are welcome!
- [ ] OPTIONAL Please, consider adding at also the Setup section - how to set up your project on the local machine (hint `git clone` command)

2022-08-24 10:07 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Aseadd,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 10:09 UTC, merged